version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: templates/Dockerfile
    ports:
      - "3000:3000"

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"